### ISSUE TITLE
Use this github user for csc department history?

### ISSUE THREAD

**Issue by jbclements** [CalPoly/csc-facebook-page#4]
Hi there! Because I have lots of other things that I should be doing, I was thinking about changing the existing department history which is represented as a wiki 

https://github.com/jbclements/CSC-department-history/wiki

... into a github pages site. If I do that, the github user that owns the repo will become part of the URL for the site, and I was thinking it would be nice if we used the CalPolyCSC user for that.

If that makes sense to you, would you consider adding me as an owner for this account? (Aha! Now you see it's all about *POWER*.)

**Comment by AndrewGuenther** [comment]
Just sent you an invite!

**Comment by jbclements** [comment]
Many thanks!

John
